
strata.labels = list(
  sex      = c("Male", "Female"),
  sex.aug  = c("Male+Female", "Male", "Female"),
  age      = c(sprintf("%d", 0:79), "80+"),
  age.fert = c(sprintf("%d-%d", seq(15,45,5), seq(19, 49, 5))),
  age.5yr = c(sprintf("%d-%d", seq(0, 75, 5), seq(4, 79, 5)), "80+"),
  age.gam = c("0-4", "5-9", "10-14", "15-19", "20-24", "25-49", "50+"),
  age.cd4.adult = c("15-24", "25-34", "35-44", "45+"),
  age.breastfeeding = c(sprintf("%d-%d", seq(0,34,2), seq(1,35,2))),
  age.csavr = c("15-19", "20-24", "25-29", "30-34", "35-39", "40-44", "45-49", "50+"),
  age.s90 = c("15-24", "25-34", "35-49", "15-49", "15+"),
  cd4.adult = c("CD4>500", "CD4 350-500", "CD4 250-349", "CD4 200-249", "CD4 100-199", "CD4 50-99", "CD4<50"),
  cd4.child.old = c("CD4>1000", "CD4 750-1000", "CD4 500-750", "CD4 350-500", "CD4 200-350", "CD4<200"),
  cd4.csavr = c("CD4>500", "CD4 350-500", "CD4 200-350", "CD4<200"),
  art.status = c("no ART", "ART"),
  arv.status = c("Not receiving ARVs", "Receiving ARVs"),
  hiv.ped = c("Off ART, perinatal HIV",
              "Off ART, HIV during breastfeeding at 0-6 months",
              "Off ART, HIV during breastfeeding at 6-12 months",
              "Off ART, HIV during breastfeeding at >12 months",
              "On ART, [0,6) months",
              "On ART, [6,12) months",
              "On ART, 12+ months"),
  art.dur = c("On ART, [0,6) months", "On ART, [6,12) months", "On ART, 12+ months"),
  art.dur.agg = c("On ART, [0,12) months", "On ART, 12+ months"),
  life.table = c("Coale-Demeny West", "Coale-Demeny North", "Coale-Demeny East", "Coale-Demeny South", "UN General", "UN Latin America", "UN Chile", "UN South Asia", "UN East Asia", "Country-specific", "Custom"),
  pmtct_time    = c("Prenatal", "Postnatal"),
  pmtct_regimen = c("Single dose NVP", "Dual ARV", "Option A", "Option B", "ART started before current pregnancy", "ART started during current pregnancy at least 4 weeks before delivery", "ART started during current pregnancy < 4 weeks before delivery"),
  kos.source = c("Case reports", "Shiny90", "CSAVR", "ECDC", "Direct"),
  vls.source = c("Routine data", "Survey data"),
  incidence.model = c("Direct", "EPP", "AEM", "CSAVR", "Mortality", "ECDC"),
  csavr.model = c("None", "Double logistic", "Single logistic", "Splines - 5 knots", "rLogistic", "Splines - 4 knots", "Splines - 3 knots"),
  csavr.source = c("Source 1", "Source 2", "Source 3"),
  epi.patterns = c("Generalized", "Concentrated non-IDU", "Concentrated IDU", "Custom", "Fitted: fixed over time", "Fitted: time-varying", "Fitted to HIV prevalence or ART", "CSAVR", "Web"),
  opt.region = c("Asia", "Central Africa", "Developed Countries", "East Africa", "Eastern Europe", "Latin America and Caribbean", "North Africa Middle East", "Southern Africa", "West Africa"),
  month = c("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"),

  ## Goals ASM constants
  ha.programs = c("Total",
                  "ART",
                  "PMTCT",
                  "VMMC",
                  "Oral PrEP",
                  "Injectable PrEP",
                  "Gel PrEP",
                  "Ring PrEP",
                  "Condom promotion",
                  "Violence prevention",
                  "HIV testing",
                  "Social asset building",
                  "Family planning",
                  "Care giver programs",
                  "Educational subsidies",
                  "Cash transfers",
                  "Economic empowerment",
                  "Teachers trained",
                  "Out of school youth",
                  "Community mobilization",
                  "FSW outreach",
                  "MSM outreach",
                  "MSM lubricants",
                  "PWID outreach",
                  "Needle and syringe exchange",
                  "OST",
                  "Program support"),

  hv.pop = c(
    "Adults",
    "Not at risk",
    "Low risk heterosexual",
    "Medium risk heterosexual",
    "High risk heterosexual",
    "People who inject drugs",
    "Men who have sex with men"),

  hv.vax = c("All",
             "Unvaccinated",
             "Vaccinated, take",
             "Vaccinated, partial",
             "Vaccinated, unprotected"),

  prep.methods = c(
    "24" = "Oral (daily)",
    "27" = "Ring",
    "33" = "Oral (monthly)",
    "34" = "Oral + contraceptive",
    "25" = "Injectable (one month)",
    "35" = "Injectable (two months)",
    "36" = "Injectable (six months)",
    "37" = "bNABs",
    "38" = "Implant",
    "39" = "PEP"),

  risk.groups = c(
    "2"  = "Low risk heterosexual",
    "3"  = "Medium risk heterosexual",
    "4"  = "High risk heterosexual",
    "5"  = "People Who Inject Drugs (PWID)",
    "6"  = "Men who have sex with men",
    "7"  = "MSM: low risk",
    "8"  = "MSM: med risk",
    "9"  = "MSM: high risk",
    "10" = "MSM: PWID"),

  rn.programs = c(
    "9"  = "General population: Community mobilization",
    "20" = "General population: Mass media",
    "19" = "General population: Voluntary counseling and testing",
    "15" = "General population: Condom provision",
    "10" = "General population: Primary students with teachers trained in AIDS",
    "11" = "General population: Secondary students with teachers trained in AIDS",
    "12" = "General population: Out-of-school youth reached",
    "13" = "General population: Young women and girls (15-24) receiving cash transfers",
    "14" = "General population: Workforce receiving STI treatment", # NOTE: May not be active in UI, but is present in .RN
    "1"  = "Key populations: Female sex workers reached by intervention",
    "2"  = "Key populations: Male sex workers reached by intervention",
    "3"  = "Key populations: MSMs reached by intervention per year",
    "27" = "Key populations: MSMs receiving lubricants",
    "4"  = "Key populations: PWID receiving harm reduction intervention",
    "5"  = "Key populations: PWID receiving counseling and testing",
    "6"  = "Key populations: PWID receiving community outreach and peer education",
    "7"  = "Key populations: PWID receiving needle and syringe exchange",
    "8"  = "Key populations: PWID receiving drug substitution",
    "26" = "Male circumcision: Males 15–49 circumcised",
    "33" = "Male circumcision: Infant males circumcised",
    "17" = "Medical services: Males with STI receiving treatment",
    "18" = "Medical services: Females with STI receiving treatment",
    "21" = "Medical services: Units of blood for transfusion tested",
    "22" = "Medical services: Post-exposure prophylaxis need that is met",
    "23" = "Medical services: Unsafe injections replaced with AD syringes",
    "24" = "Medical services: Reduction in number of other injections",
    "25" = "Medical services: Hospital beds covered by universal precautions"),

  rn.unit.costs.general = c(
    # General Population
    "9"   = "Community mobilization: Cost per person reached",
    "18"  = "Mass media: Cost per person reached",
    "17"  = "HIV testing: Cost per VCT client",
    "15"  = "Condom provision: Cost per male condom distributed by the public sector",
    "10"  = "Youth: Cost per teacher trained in primary school education",
    "11"  = "Youth: Cost per teacher trained in secondary school education",
    "12"  = "Youth: Cost per peer education for out of school youth",
    "13"  = "Economic strengthening: Cost per woman receiving economic strengthening (per year)",
    # Key populations
    "1"   = "Cost per sex worker targeted (FSW)",
    "2"   = "Cost per sex worker targeted (MSW)",
    "3"   = "Cost per MSM targeted",
    "29"  = "Cost of MSM lubricants per person",
    "4"   = "Cost of harm reduction programs per person contacted (PWID)",
    "5"   = "Cost of counseling and testing per PWID targeted",
    "6"   = "Cost of community outreach and peer education per PWID targeted",
    "7"   = "Cost per needle distributed and destroyed",
    "8"   = "Cost of drug substitution per PWID targeted",
    # Medical services
    "16"  = "STI management: Cost per STI treated in clinics",
    "19"  = "Blood safety: Cost of screening a unit of blood for HIV",
    "20"  = "Post-exposure prophylaxis: Cost per PEP kit",
    "21"  = "Safe medical injection: Additional cost for AD syringes",
    "22"  = "Universal precautions: Annual cost per hospital bed",
    # Male circumcision
    "23"  = "Cost per adult circumcision",
    "32"  = "Cost per infant circumcision",
    # PrEP
    "24"  = "PrEP oral: Cost per person treated (Daily)",
    "33"  = "PrEP oral: Cost per person treated (Monthly)",
    "34"  = "PrEP oral: Cost per person treated (Plus Contraceptive)",
    "25" = "PreP injectable: Cost per person treated (1 Month)",
    "35" = "PrEP injectable: Cost per person treated (2 Months)",
    "36"  = "PrEP injectable: Cost per person treated (6 Months)",
    "27"  = "PrEP ring: Cost per person treated",
    "37"  = "PrEP bNABs: Cost per person treated",
    "38"  = "PrEP Implant: Cost per person treated",
    "39"  = "PrEP PEP: Cost per person treated",
    # Vaccines
    "28"  = "Vaccines: Cost per person fully vaccinated",
    # Cure
    "40"  = "PLHIV: Cost per person treated (Cure)",
    # AHD treatment
    "41"  = "PLHIV: Cost per person treated (AHD treatment)"),

  rn.unit.costs.treatment = c(
    "<FirstLineARTDrugs MV>" = "First line ART drugs",
    "<SecondLineARTDrugs MV>" = "Second line ART drugs",
    "<AdditARTDrugCostsTBmale MV>" = "Additional ART drug costs for TB patients (male)",
    "<AdditARTDrugCostsTBfemale MV>" =  "Additional ART drug costs for TB patients (Female)",
    "<LabCostsARTTr MV>"= "Lab costs for ART treatment",
    "<DrugLabCostsTrInf MV>" = "Lab costs for drugs to treat infections",
    "<CotrimProphylaxis MV>" = "Cotrimoxazole prophylaxis",
    "<TBProphylaxis MV>" = "TB prophylaxis",
    "<NutritionSuppSixMo MV>" = "Nutrition supplements in first six months",
    "<ChildrenARVDrugs MV>" = "Children ARV drugs",
    "<ChildrenLabCostsARTTr MV>" = "Children ART treatment lab costs",
    "<CostPerInpatientDay MV>" = "Cost per in-patient day",
    "<CostPerOutpatientDay MV>" = "Cost per out-patient visit",
    "<ARTinpatientDays MV>" = "ART: in-patient days",
    "<ARToutpatientDays MV>" = "ART: out-patient visit",
    "<OItreatmentInpatientDays MV>" = "OI treatment: in-patient days",
    "<OItreatmentOutpatientDays MV>" = "OI treatment: out-patient days"),

  rn.unit.costs.pmtct = c(
    "<Mother MV>" = "HIV testing (per test): Mother"
  ),

  ## Goals RSM constants
  rsm.infectiousness.stages = c(
    "Primary Infection",
    "Asymptomatic stage",
    "Symptomatic stage (no ART)"),

  rsm.impact.interventions = c(
    "Community mobilization",
    "Mass media",
    "VCT",
    "Condoms",
    "Youth in school",
    "Youth out of school",
    "Economic strengthening",
    "Sex workers",
    "MSM outreach",
    "MSM: lubricants",
    "PWID outreach",
    "PWID: needle exchange",
    "PWID: drug substitution"),

  rsm.impact.outcomes = c(
    "Condom_nonuse_High",
    "Condom_nonuse_Medium",
    "Condom_nonuse_Low",
    "Condom_nonuse_MSM",
    "Condom_nonuse_PWID",
    "Partners_High",
    "Partners_Medium",
    "Partners_Low",
    "Partners_MSM",
    "Partners_PWID",
    "AgeFirstSex_Medium",
    "Unsafe_injecting",
    "Needle_sharing",
    "Sharing_partners"),

  rsm.fit.param.names = c(
    "Transmission of HIV per act",
    "Transmission multiplier male-to-female",
    "Transmission multiplier for STI",
    "Transmission multiplier for MSM contacts",
    "Months in primary stage",
    "Primary infection relative infectiousness",
    "Symptomatic stage infectiousness (no ART)",
    "Initial pulse size",
    "Sex acts per partner: Low risk heterosexual",
    "Sex acts per partner: Medium risk heterosexual",
    "Sex acts per partner: High risk heterosexual",
    "Sex acts per partner: MSM",
    "Percent PWID sharing needles",
    "Condom use growth rate",
    "Condom use growth location",
    "Years to final condom use value",
    "Unused")
)

output.labels = list(
  value = "Value"
)

strata.labels$hv.hiv = c("Negative", "Primary", strata.labels$cd4.adult)
strata.labels$hv.pop.ext = c( "All",
                             strata.labels$hv.pop[2:7],
                             "MSM, low risk",
                             "MSM, medium risk",
                             "MSM, high risk",
                             "MSM who inject drugs")
strata.labels$rsm.condom.groups = c(strata.labels$hv.pop[c(3,4,5,7)],
                                    "MSM: low risk",
                                    "MSM: medium risk",
                                    "MSM: high risk")

## Short acronym labels for Key populations: ... programme names, used to keep
## facet strip text readable (full labels are too long to fit multi-panel
## plots, especially across many pages of a saved PDF).
#' @noRd
kp.programme.labels = c(
  "Key populations: Female sex workers reached by intervention" = "KP: FSW reached",
  "Key populations: Male sex workers reached by intervention" = "KP: MSW reached",
  "Key populations: MSMs reached by intervention per year" = "KP: MSM reached",
  "Key populations: MSMs receiving lubricants" = "KP: MSM lubricants",
  "Key populations: PWID receiving harm reduction intervention" = "KP: PWID harm reduction",
  "Key populations: PWID receiving counseling and testing" = "KP: PWID counseling/testing",
  "Key populations: PWID receiving community outreach and peer education" = "KP: PWID outreach",
  "Key populations: PWID receiving needle and syringe exchange" = "KP: PWID needle exchange",
  "Key populations: PWID receiving drug substitution" = "KP: PWID drug substitution")

dp_not_avail = -9999 # Value used to indicate missing data in DemProj
